# Generated by Django 2.2.3 on 2021-05-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'insights'), ('2', 'resources')], default='1', max_length=20)),
            ],
            options={
                'verbose_name': '版块',
                'verbose_name_plural': '版块',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='channel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Channel', verbose_name='版块'),
        ),
    ]
