# Generated by Django 2.2.3 on 2021-05-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210522_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Channel', verbose_name='版块'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.IntegerField(choices=[(1, 'insights'), (2, 'resources')], default=1, max_length=20),
        ),
    ]
