# Generated by Django 2.2.3 on 2021-05-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210523_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='desc',
            field=models.CharField(default='Your channel description here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Your channel name here.', max_length=20),
        ),
    ]
