# Generated by Django 2.2.3 on 2021-05-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210526_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('Insights', '洞察'), ('Resources', '资源')], default='洞察', max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
