# Generated by Django 2.2.3 on 2021-06-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=250, verbose_name='摘要'),
        ),
    ]
